spring:
  application:
    name: turbine
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://eureka:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
turbine:
  instanceUrlSuffix:
    default: /hystrix.stream
  app-config: provider
  cluster-name-expression: "'default'"
  combine-host-port: true

