server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
    register-with-eureka: false
    fetch-registry: true
spring:
  application:
    name: consumer
